### PR TITLE
Adds support to fetch data for corresponding TRI index

### PR DESCRIPTION
**Pull request by kdhere16**
Will add a little later.

### CODE REVIEW

**Review by crimelabs786 — APPROVED** [review]
Looks good.

Can we start with adding new Python 3 typings or Pydantic as well?

**Comment by crimelabs786** [comment]
@kdhere16 If we're keeping this branch open, better mark it as protected branch in branch protection rules

**Comment by kdhere16** [comment]
> @kdhere16 If we're keeping this branch open, better mark it as protected branch in branch protection rules. And convert this PR to a draft PR.

@crimelabs786 Made some changes:

- Forked branch `bosforus-master` from `master`
- Changed the base of this PR to `bosforus-master`
- Set the default branch of this repository to `bosforus-master`, just to keep things clean

**Comment by kdhere16** [comment]
@crimelabs786 I think we could merge this PR? Will create a separate issue to add typings support to this library.

**Pull request merged**
